### ISSUE TITLE
Suggestion: Add wrapper shell script

### ISSUE THREAD

**Issue by jukx** [Phanx/wow-addon-updater#17]
`lua xxx.lua` is a bit unwieldy. Consolidating both functions into one script makes a lot of sense, especially when you want to use the application from the command line in daily use.

The only issue would be to determine the AddOns directory.

I'm using this one:
```
#!/bin/sh

cd "/mnt/games/World of Warcraft/Interface/AddOns/updater"
if [[ -z $1 ]]; then
    lua update.lua
else
    lua install.lua "$@"
fi
```

**Comment by Phanx** [comment]
This should work:

1. Replace the `cd` line with `cd "$(dirname "$0")"`
2. Leave the script in the updater directory
3. `ln -s` the script into a directory that's in your PATH

You can leave your shell script in the updater directory, `ln -s` it to somewhere in your PATH, use

**Comment by jukx** [comment]
Doesn't get the correct path to the script via $0 when you run the linked file.
Another case of ["which systems are going to be supported?"](https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself)
:(

**Comment by Phanx** [comment]
I definitely have some scripts up that way, though I may have misremembered the exact syntax. I'll check and report back.

**Comment by jukx** [comment]
Thanks, that would be great!

**Comment by Phanx** [comment]
Try `cd "$(dirname "$(readlink -f "$0")")"`
