### ISSUE TITLE
Bug in update.lua: doesn't remember all addons

### ISSUE THREAD

**Issue by jukx** [Phanx/wow-addon-updater#2]
_Edit: Actually it's the case for all of them. I had ignored Details previously, after unignoring the same thing happens here._

---

I am using some addons to test update.lua. After going through all and matching/ignoring them, some of them don't seem to be remembered.
In my case, that's **BugSack**, **!BugGrabber** and **AdiBags**.
Every time I run `lua update.lua` he tells me that he's found them anew. They do get saved in db.lua though:
```
	["AdiBags"] = {
		["version"] = "v1.9.8";
		["dir"] = "AdiBags";
		["id"] = "adibags";
		["author"] = "Adirelle";
		["title"] = "AdiBags";
		["wow"] = "70300";
	};
```

Same behaviour with Lua 5.1 and 5.3.4

My addons:
![addons](https://user-images.githubusercontent.com/37248737/38548704-b4a360f0-3cb2-11e8-9d1a-35eba2546f1b.png)

**Comment by jukx** [comment]
Apparently the match function doesn't set the meta.site parameter which is checked against at the start of update.lua.

**Comment by Phanx** [comment]
I'll investigate this further later in the week.
