### ISSUE TITLE
Needs error message when invalid url is entered

### ISSUE THREAD

**Issue by jukx** [Phanx/wow-addon-updater#4]
Right now it just says "Usage: `lua install.lua <url>` or `lua install.lua <site> <id>`" when passing a www.curseforge.com url or similar.

**Comment by Phanx** [comment]
As per the README:

> For CurseForge, the www.curseforge.com domain (user site) is not supported; click the link to view the addon's "project page" and use that URL, which will either be on wow.curseforge.com or www.wowace.com.

Feel free to open a PR if you want to add support for the new www site; you'd need to fetch the page, find the "project page" link, extract the URL, and run the function again with that URL instead of the original user supplied one.

**Comment by Phanx** [comment]
I did consider it myself, but decided it wasn't worth the time given how infrequently addons actually get installed, and how I never use the www domain since it's just a neutered version of the project page.

**Comment by jukx** [comment]
My issue is not so much with www.curseforge.com but the lack of information about what went wrong. Even if you have a typo in the url etc. Since the tool is called **wow-addon-updater** I can understand that the installer is not a big priority, though.
