### ISSUE TITLE
install.lua: ignore non-main folders?

### ISSUE THREAD

**Issue by jukx** [Phanx/wow-addon-updater#9]
So, tell me if I understand this updater correctly: There's one main folder which is used to find the addon on $addonsite and the other folders can/should be ignored.

If that's correct wouldn't it make sense to automatically ignore all non-main folders upon installation?

**Comment by Phanx** [comment]
Yes, your understanding is correct, and yes, that probably should happen. However, as you correctly guessed in the other thread, the installer feature was mostly an afterthought, and I've only used it a few times, so I'm not even remotely surprised it needs work. I'll look at this tomorrow or so unless you beat me to it with a PR.

**Comment by jukx** [comment]
Ah, alright! Well this isn't really urgent, but would definitely be nice to have at some point in the future.

**Comment by Phanx** [comment]
Closing this in favor of the PR.
